name: CI/CD Node.js - Générateur de citations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: # Job CI
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy: # Job CD
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dynamic index.html
        run: |
          echo '<!DOCTYPE html>' > public/index.html
          echo '<html lang="fr"><head><meta charset="UTF-8"><title>TP Node.js CI/CD</title></head>' >> public/index.html
          echo '<body>' >> public/index.html
          echo '<h1>✨ Générateur de citations ✨</h1>' >> public/index.html
          echo '<p id="citation"></p>' >> public/index.html
          echo '<script type="module">' >> public/index.html
          echo 'import citationAleatoire from "../src/app.js";' >> public/index.html
          echo 'document.getElementById("citation").innerText = citationAleatoire();' >> public/index.html
          echo '</script>' >> public/index.html
          echo '</body></html>' >> public/index.html
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
